version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper001
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"

    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper001:2181